[project]
authors = ["horned_axe <horned_axe@proton.me>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "lung_image"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
opencv = "*"
numpy = "*"
pytorch = "*"
torchvision = "*"